<a href="https://colab.research.google.com/github/SaiHarshitha-192/Heart-dataset/blob/main/Heart_Attack.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#HEART DATASET

import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.model_selection import train_test_split

#loading dataset
X=pd.read_csv('/content/drive/MyDrive/heart.csv')
print(X)

#true facts of dataset
print(X.head())
print(X.tail())
print(X.keys())

     age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
0      0      1       1  

In [2]:
#splitting dataset into test and train
from sklearn.model_selection import train_test_split
features=X.iloc[:,0:13]
target=X.iloc[:,13]
print(features)
print(target)

     age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  
0      0      1  
1      0      2

In [3]:
X_train, X_test, Y_train, Y_test = train_test_split(features,target, test_size=0.2, train_size=0.8, random_state=0)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)


(242, 13)
(61, 13)
(242,)
(61,)


In [5]:
#Logistic regression
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
print(log_reg)

log_reg.fit(X_train,Y_train.values.ravel())

#Measure the SCore
l=log_reg.score(X_test,Y_test)


#Predicting of Testing Data
l=log_reg.predict(X_train[10:20])
print(X_train[10:20])
print(l)


LogisticRegression()
     age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
46    44    1   2     140   235    0        0       180     0      0.0    2   
160   56    1   1     120   240    0        1       169     0      0.0    0   
232   55    1   0     160   289    0        0       145     1      0.8    1   
181   65    0   0     150   225    0        0       114     0      1.0    1   
27    51    1   2     110   175    0        1       123     0      0.6    2   
173   58    1   2     132   224    0        0       173     0      3.2    2   
261   52    1   0     112   230    0        1       160     0      0.0    2   
37    54    1   2     150   232    0        0       165     0      1.6    2   
101   59    1   3     178   270    0        0       145     0      4.2    0   
166   67    1   0     120   229    0        0       129     1      2.6    1   

     caa  thall  
46     0      2  
160    0      2  
232    1      3  
181    3      3  
27     0      2  
1

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [6]:
#KNN classifier
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier()
knn_clf.fit(X_train, Y_train)
l=knn_clf.predict(X_train[10:20])
print(l)
l=knn_clf.score(X_test,Y_test)
print(l)

[1 1 0 0 0 1 0 1 0 0]
0.639344262295082


In [7]:
#SGD classifier
from sklearn.linear_model import SGDClassifier
sgd_clf = SGDClassifier()
sgd_clf.fit(X_train, Y_train)
l = sgd_clf.predict(X_train[10:20])
print(l)
c=sgd_clf.score(X_test, Y_test)
print(c)

[1 1 0 0 1 1 1 1 0 0]
0.6721311475409836


In [8]:
#Cross validation evaluation
from sklearn.model_selection import cross_val_score
cross_val_score(sgd_clf, X_train, Y_train, cv=5, scoring="accuracy")
from sklearn.model_selection import cross_val_predict
Y_train_pred = cross_val_predict(sgd_clf, X_train, Y_train, cv=3)
print(Y_train_pred)
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_train, Y_train_pred)
print("Confusion Matrix")
print(matrix)
from sklearn.metrics import precision_score, recall_score
print("Precision:", precision_score(Y_train, Y_train_pred, average='micro'))
print("Recall:", recall_score(Y_train, Y_train_pred,average='micro'))
from sklearn.metrics import f1_score
print("F1 score:", f1_score(Y_train, Y_train_pred, average='micro'))

[1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 0 0 1
 1 0 0 1 0 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0
 1 1 1 1 1 1 0 1 1 0 1 1 1 0 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1
 0 1 1 1 1 1 1 1 1 0 0 1 1 1 0 1 0 1 1 1]
Confusion Matrix
[[ 21  90]
 [  6 125]]
Precision: 0.6033057851239669
Recall: 0.6033057851239669
F1 score: 0.6033057851239669


In [9]:
#SVM
from sklearn import svm, datasets
svc = svm.SVC(kernel='linear', C=1).fit(X_train, Y_train)
c=svc.score(X_test, Y_test)
print(c)


0.819672131147541
